# Generated by Django 4.1.1 on 2022-09-14 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_newblog"),
    ]

    operations = [
        migrations.AlterField(
            model_name="newblog",
            name="author",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Author"
            ),
        ),
        migrations.AlterField(
            model_name="newblog",
            name="owner",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Owner"
            ),
        ),
        migrations.AlterField(
            model_name="newblog",
            name="title",
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name="Title"
            ),
        ),
    ]
