# Generated by Django 4.1.1 on 2022-09-14 22:30

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_newblog_author_alter_newblog_owner_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="NewReview",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("timestamp", models.DateTimeField(auto_now_add=True)),
                (
                    "owner",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Owner"
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Title"
                    ),
                ),
                (
                    "author",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Author"
                    ),
                ),
                ("review", ckeditor.fields.RichTextField(blank=True, null=True)),
                ("slug", models.SlugField(blank=True, null=True)),
                ("image", models.ImageField(blank=True, null=True, upload_to="blog")),
                ("is_active", models.BooleanField(default=True)),
            ],
            options={
                "verbose_name": "New Review",
                "verbose_name_plural": "New Reviews",
                "ordering": ["timestamp"],
            },
        ),
    ]
