# Generated by Django 4.1.1 on 2022-09-18 01:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_newreview"),
    ]

    operations = [
        migrations.DeleteModel(name="NewBlog",),
        migrations.DeleteModel(name="NewReview",),
    ]
